// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Data;

#nullable disable

namespace ProductManagement.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241106162736_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ace77301-fc64-4da9-bb59-9657d3335b28"),
                            CreatedDate = new DateTime(2024, 11, 6, 19, 27, 35, 864, DateTimeKind.Local).AddTicks(6429),
                            IsDeleted = false,
                            Name = "Elma",
                            Price = 15m,
                            ProductCode = "ELMA",
                            ProductImage = "https://upload.wikimedia.org/wikipedia/commons/1/15/Red_Apple.jpg"
                        },
                        new
                        {
                            Id = new Guid("2d8d45f6-80e0-4acc-9685-652da49bc67b"),
                            CreatedDate = new DateTime(2024, 11, 6, 19, 27, 35, 864, DateTimeKind.Local).AddTicks(6438),
                            IsDeleted = false,
                            Name = "Muz",
                            Price = 30m,
                            ProductCode = "MUZ",
                            ProductImage = "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d2f62e3e-4db4-4ae7-a9f7-96c5d90f77fc"),
                            IsDeleted = false,
                            Password = "GGz3dMl7YKHBBu9xjRCXCmoG4GvviVU9muZdk4qIbq4=",
                            UserType = 1,
                            Username = "superadmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
